### ISSUE TITLE
好厉害~爱了

### ISSUE THREAD

**Issue by RidiculousDoge** [wang-weize/wkfg-spider#1]

**Comment by wang-weize** [comment]
你知道提交和关闭issue都会发邮件吗/huaji/xinsui




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wang-weize/wkfg-spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月22日(星期四) 上午10:13
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [wang-weize/wkfg-spider] 好厉害~爱了 (#1)





 
Closed #1.
